# Generated by Django 5.2.6 on 2025-10-10 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '0004_alter_brand_image_name_alter_product_image_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderDetials',
            new_name='OrderDetails',
        ),
    ]
