# Generated by Django 5.0.3 on 2025-10-07 12:53

import django.utils.timezone
import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('mobile_number', models.CharField(max_length=11, unique=True, verbose_name='شماره تلفن')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='نام')),
                ('family', models.CharField(blank=True, max_length=50, verbose_name='نام خانوادگی')),
                ('email', models.EmailField(blank=True, max_length=200, verbose_name='ایمیل')),
                ('gender', models.CharField(blank=True, choices=[('True', 'مرد'), ('False', 'زن')], default='True', max_length=50, null=True, verbose_name='جنسیت')),
                ('image_name', models.ImageField(blank=True, null=True, upload_to=utils.UploadFile.upload_to, verbose_name='عکس پروفایل')),
                ('register_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت نام')),
                ('is_active', models.BooleanField(default=False, verbose_name='وضعیت')),
                ('active_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='کد فعالسازی')),
                ('is_admin', models.BooleanField(default=False, verbose_name='ادمین')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
            },
        ),
    ]
